pin to rust version that has functional clippy
We get the following error for stage1 + clippy:

  --- stderr
     Compiling stage1 v0.1.0 (/home/joerg/git/vmsh/src/stage1)
  error: failed to run custom build command for `stage1 v0.1.0 (/home/joerg/git/vmsh/src/stage1)`

  Caused by:
    process didn't exit successfully: `/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-3719533929c4c8b7/build-script-build` (exit status: 101)
    --- stdout
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/namespace.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/user_namespace.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/mountns.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/sys_ext/mod.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/sys_ext/internal/mod.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/sys_ext/internal/mknodat.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/sys_ext/internal/prctl.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/dir.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/block.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/cmd.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/console.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/kmsg.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/mount_context.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/procfs/mod.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/procfs/unix.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/lsm.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/capabilities.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/main.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/result.rs
    cargo:rerun-if-changed=/home/joerg/git/vmsh/src/stage1/src/../../stage2/src/cgroup.rs
    cargo:rustc-link-search=/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out
    TARGET = Some("x86_64-unknown-linux-gnu")
    OPT_LEVEL = Some("z")
    HOST = Some("x86_64-unknown-linux-gnu")
    CC_x86_64-unknown-linux-gnu = None
    CC_x86_64_unknown_linux_gnu = None
    HOST_CC = None
    CC = Some("gcc")
    CFLAGS_x86_64-unknown-linux-gnu = None
    CFLAGS_x86_64_unknown_linux_gnu = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("false")
    CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
    running: "gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out/trampoline.o" "-c" "trampoline.S"
    exit status: 0
    AR_x86_64-unknown-linux-gnu = None
    AR_x86_64_unknown_linux_gnu = None
    HOST_AR = None
    AR = Some("ar")
    running: "ar" "cq" "/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out/libtrampoline.a" "/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out/trampoline.o"
    exit status: 0
    running: "ar" "s" "/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out/libtrampoline.a"
    exit status: 0
    cargo:rustc-link-lib=static=trampoline
    cargo:rustc-link-search=native=/home/joerg/git/vmsh/src/stage1/target/release/build/stage1-d29c05c4ce1a7a09/out
    cargo:rerun-if-changed=trampoline.S
    vmsh/build.rs:31: Executing "cargo" "build" "--release" "--target=x86_64-unknown-linux-gnu"

    --- stderr
       Compiling stage2 v0.1.0 (/home/joerg/git/vmsh/src/stage2)
    memory allocation of 18446744073709551615 bytes failed
    error: could not compile `stage2`